# This is a basic workflow to help you get started with Actions

name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["develop", "gh-pages"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Update version'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

#authorization to private github
permissions:
  contents: write
  actions: write
  checks: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  verif:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ pre-commit ]
    name: Vérifications

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm ci
      - name: Run TU
        run: npm run test:coverage
      - name: Run lint
        run: npm run lint
      - name: Publish TU Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Vitest Tests                  # Name of the check run which will be created
          path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ verif ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install nuxt
        run: npm install nuxt
      - name: Run a one-line script
        run: npm run build

  # log-the-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "Log level: $LEVEL"
  #       env:
  #         LEVEL: ${{ inputs.logLevel }}


  increment-version:
      if: github.event_name == 'workflow_dispatch'
      runs-on: ubuntu-latest
      needs: [ build ]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - run: |
            echo "Update version: $VERSION"
          env:
            VERSION: ${{ inputs.version }}

        - name: Incrémenter la version
          run: npm version $VERSION
          env:
            VERSION: ${{ inputs.version }}

        - name: Commit changes
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add package.json
            git commit -m "Incrementing version"
            git push

        - name: Package Node
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}


  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   needs: [ build ]
  #   permissions:
  #     contents: write # to be able to publish a GitHub release
  #     issues: write # to be able to comment on released issues
  #     pull-requests: write # to be able to comment on released pull requests
  #     id-token: write # to enable use of OIDC for npm provenance
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: npm clean-install
  #     - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
  #       run: npm audit signatures
  #     - name: Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PAT }}
  #         NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}
  #       run: npm run release

  deploy_mkdocs:
    needs: [ pre-commit ]
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Mkdocs
        run: pip install -r requirements.txt
      - name: Build Mkdocs
        run: mkdocs build --config-file docs/mkdocs.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4

  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
