# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["develop", "gh-pages"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#authorization to private github
permissions:
  contents: read
  actions: read
  checks: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  verif:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Vérifications

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm ci
      - name: Run TU
        run: npm run test:coverage
      - name: Run lint
        run: npm run lint
      - name: Publish TU Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Vitest Tests                  # Name of the check run which will be created
          path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PAT }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PAT }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      # - name: Build docker containers
      #   run: docker-compose -f "./docker-compose.yml" build frontend
      - name: Update package.json with version from .cz.toml
        run: |
          VERSION=$(grep -oP 'version = "\K[^"]+' .cz.toml)
          npm version $VERSION
      - name: Package Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}



  deploy_mkdocs:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PAT }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Mkdocs
        run: pip install -r requirements.txt
      - name: Build Mkdocs
        run: mkdocs build --config-file docs/mkdocs.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
